'use client';
import {useState} from 'react';

async function jsonFetch(url:string,init:RequestInit){const response=await fetch(url,init),data=await response.json();if(!response.ok)throw new Error(data.error||'Request failed');return data}
export function Logout(){return <button onClick={async()=>{await fetch('/api/admin/logout',{method:'POST'});location.href='/admin/login'}}>LOG OUT</button>}

export function CustomerControls({customerId,currentStatus}:{customerId:string;currentStatus:string}){const [status,setStatus]=useState(currentStatus),[note,setNote]=useState(''),[message,setMessage]=useState('');return <section className="admin-controls"><label>RELATIONSHIP STATUS<select value={status} onChange={event=>setStatus(event.target.value)}><option value="new">New</option><option value="engaged">Engaged</option><option value="reserved">Reserved</option><option value="client">Client</option><option value="inactive">Inactive</option></select></label><button onClick={async()=>{try{await jsonFetch(`/api/admin/customers/${customerId}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({current_status:status})});setMessage('Status saved.')}catch(error){setMessage(error instanceof Error?error.message:'Could not save.')}}}>SAVE STATUS</button><label>INTERNAL NOTE<textarea value={note} onChange={event=>setNote(event.target.value)} placeholder="Add context for the ASTRELI team…"/></label><button disabled={!note.trim()} onClick={async()=>{try{await jsonFetch('/api/admin/notes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customerId,note})});setNote('');setMessage('Note added.')}catch(error){setMessage(error instanceof Error?error.message:'Could not save.')}}}>ADD NOTE</button>{message&&<small>{message}</small>}</section>}

export function DraftReply({customerName,summary,conversationId}:{customerName?:string;summary?:string;conversationId?:string}){const [draft,setDraft]=useState(''),[loading,setLoading]=useState(false),[message,setMessage]=useState('');return <section className="admin-composer"><div><button onClick={async()=>{setLoading(true);try{const data=await jsonFetch('/api/admin/draft',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customerName,summary,history:[]})});setDraft(data.draft||'Draft unavailable')}catch(error){setMessage(error instanceof Error?error.message:'Draft unavailable')}finally{setLoading(false)}}}>{loading?'DRAFTING…':'DRAFT WITH AI'}</button>{conversationId&&<button onClick={async()=>{try{await jsonFetch(`/api/admin/conversations/${conversationId}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({human_takeover:true,status:'human_takeover'})});setMessage('Conversation assigned to a human.')}catch(error){setMessage(error instanceof Error?error.message:'Could not update.')}}}>TAKE OVER AS HUMAN</button>}</div><textarea value={draft} onChange={event=>setDraft(event.target.value)} placeholder="Draft a personal reply…"/><small>Draft only. Nothing is sent automatically. Email and WhatsApp remain disabled until configured.</small><button disabled={!draft||!conversationId} onClick={async()=>{try{await jsonFetch(`/api/admin/conversations/${conversationId}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content:draft})});setDraft('');setMessage('Human-approved reply stored in the conversation history.')}catch(error){setMessage(error instanceof Error?error.message:'Could not store reply.')}}}>STORE HUMAN-APPROVED REPLY</button>{message&&<small>{message}</small>}</section>}
