'use client';
import Image from 'next/image';
import Link from 'next/link';
import {ArrowLeft,ArrowRight,MessageCircle} from 'lucide-react';
import {Product} from '@/data/catalog';
import {socialPrice} from '@/data/social-commerce';
import SocialHeader from './SocialHeader';
import {useStylist} from './StylistProvider';

const money=(value:number)=>`RM ${value.toLocaleString('en')}`;
function ProductImage({product}:{product:Product}){const position=`${(product.sprite%4)*33.333}% ${product.sheet==='electric'?Math.floor(product.sprite/4)*100:Math.floor(product.sprite/4)*50}%`;return <div className={`product-art ${product.sheet==='electric'?'electric-art':''}`} role="img" aria-label={`Studio photograph of ${product.name}`} style={product.image?{backgroundImage:`url(${product.image})`,backgroundPosition:'center',backgroundSize:'cover'}:{backgroundPosition:position}}/>}
export default function ProductDetail({product}:{product:Product}){const {openChat}=useStylist();return <div className="social-product-page"><div className="social-announcement">DROP 01 · COLOUR POP · KUALA LUMPUR</div><SocialHeader/><main><section className="pdp-editorial"><div className="pdp-model"><Image src={`/images/models/${product.id}.jpg`} fill priority sizes="(max-width: 800px) 100vw, 58vw" alt={`ASTRELI wearing ${product.name}`}/><span>WORN BY ASTRELI</span></div><div className="pdp-intro"><Link href="/#drop"><ArrowLeft/> BACK TO DROP 01</Link><small>DROP 01 · COLOUR POP</small><h1>{product.name}</h1><strong>{money(socialPrice(product))}</strong><p>{product.description}</p><dl><div><dt>MATERIAL</dt><dd>{product.metal}</dd></div><div><dt>DIAMOND</dt><dd>{product.carat} lab-grown · {product.color}</dd></div><div><dt>COLLECT</dt><dd>ASTRELI Night or delivery</dd></div></dl><button onClick={()=>openChat(product)}>INTERESTED? LET’S TALK <MessageCircle/></button><button className="pdp-reserve" onClick={()=>openChat(product,'reserve')}>RESERVE FOR ASTRELI NIGHT <ArrowRight/></button><small className="pdp-note">No payment is taken in this preview. ASTRELI confirms every reservation personally.</small></div></section><section className="pdp-gallery"><div><ProductImage product={product}/><span>THE PIECE</span></div><div><Image src="/images/astreli-materials-detail.jpg" fill sizes="50vw" alt="Lab-grown diamonds and sterling silver"/><span>LAB DIAMONDS · SILVER AT THE CORE</span></div></section><section className="pdp-story-social"><small>WHY THIS ONE</small><h2>Looks like a lot.<br/>Costs less than you think.</h2><p>The design comes first. Lab-grown diamonds make the colour and scale possible; silver keeps the piece modern, wearable and within reach.</p><button onClick={()=>openChat(product)}>ASK ASTRELI ABOUT IT <ArrowRight/></button></section></main><footer className="social-footer"><Link className="social-logo" href="/">ASTRELI<span>LABS IN SILVER</span></Link><nav><Link href="/astreli-night">ASTRELI Night</Link><Link href="/contact">Contact</Link><Link href="/delivery-returns">Delivery</Link><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></nav><p>© 2026 ASTRELI · KUALA LUMPUR</p></footer></div>}
