'use client';
import Image from 'next/image';import Link from 'next/link';import {ArrowDownRight,ArrowRight,Play,Share2} from 'lucide-react';
import {currentDrop,featuredProducts,nextNight,socialPrice} from '@/data/social-commerce';import {Product,productSlug} from '@/data/catalog';import {useStylist} from './StylistProvider';import SocialHeader from './SocialHeader';import {track} from '@/lib/social-analytics';
const money=(value:number)=>`RM ${value.toLocaleString('en')}`;function ProductVisual({product}:{product:Product}){return <div className="social-product-visual"><Image src={`/images/models/${product.id}.jpg`} fill sizes="(max-width: 700px) 100vw, 52vw" alt={`ASTRELI wearing ${product.name}`}/></div>}
export default function Storefront(){const {openStylist}=useStylist();const invite=async()=>{track('friend_invite');const url=`${location.origin}/astreli-night?ref=friend`;if(navigator.share)await navigator.share({title:'ASTRELI Night',text:'Come to ASTRELI Night with me.',url});else await navigator.clipboard.writeText(url)};return <><div className="social-announcement">DROP 01 · COLOUR POP · WAITLIST OPEN</div><SocialHeader/><main className="social-home waitlist-home">
 <section className="social-hero"><Image src="/images/social-hero.jpg" fill priority sizes="100vw" alt="ASTRELI and friends arriving at a Kuala Lumpur jewellery night"/><div className="social-hero-shade"/><div className="social-hero-copy"><small>YOUR PERSONAL JEWELLERY STYLIST</small><h1>FIND YOUR<br/>PIECE.<br/><em>WE’LL TAKE IT<br/>FROM THERE.</em></h1><p>A small edit, chosen with you and made in batches. Join the list for anything you love — we’ll tell you when the next batch is ready.</p><div><button onClick={()=>{track('hero_cta_click',{cta:'find_my_piece'});openStylist()}}>FIND MY PIECE <ArrowRight/></button><a href="#drop">EXPLORE THE DROP <ArrowDownRight/></a></div></div><span className="hero-side">PERSONAL STYLIST · WAITLIST · DROP · ASTRELI NIGHT</span></section>
 <section id="drop" className="drop-intro"><div><small>CURRENT DROP · NEXT BATCH FORMING</small><h2>COLOUR<br/>POP</h2></div><p>{currentDrop.line}<br/><span>{currentDrop.description}</span></p></section>
 <section className="made-in-drops"><small>MADE IN DROPS</small><h2>WE MAKE ASTRELI<br/>IN SMALL BATCHES.</h2><p>Join the list for a piece you love. When enough people want it, we make the next batch — and you get first access.</p><div><span>NO PAYMENT WHEN YOU JOIN</span><a href="#pieces">EXPLORE THE DROP <ArrowRight/></a></div></section>
 <section id="pieces" className="editorial-products waitlist-products">{featuredProducts.map((product,index)=><article className={index%2?'reverse':''} key={product.id}><ProductVisual product={product}/><div><small>NEXT BATCH FORMING · 0{index+1}</small><h3>{product.name}</h3><strong>{money(socialPrice(product))}</strong><p>{product.description}</p><span>NO PAYMENT YET · FIRST ACCESS WHEN THE BATCH OPENS<br/>{product.carat} · {product.metal}</span><Link href={`/products/${productSlug(product)}`}>SEE THE PIECE <ArrowRight/></Link><button onClick={()=>{track('join_list_clicked',{product:product.name,status:'batch_forming'});openStylist({product,mode:'waitlist'})}}>JOIN THE LIST <ArrowRight/></button></div></article>)}</section>
 <section className="stylist-feature"><div><small>YOUR ASTRELI STYLIST</small><h2>NOT SURE<br/>WHERE TO START?</h2><p>Tell us what you like, where you’ll wear it and what feels comfortable. Your stylist will show you two or three pieces worth seeing — not twenty.</p><button onClick={()=>openStylist()}>FIND MY PIECE <ArrowRight/></button></div><div className="stylist-feature-image"><Image src="/images/astreli-pdp-model.jpg" fill sizes="(max-width: 800px) 100vw, 50vw" alt="ASTRELI personal jewellery stylist edit"/></div></section>
 <section className="how"><header><small>A SMALL COMMITMENT, THEN THE RIGHT ONE</small><h2>HOW ASTRELI WORKS</h2></header><div>{[['01','DISCOVER','Find something you love.'],['02','TALK','Your stylist helps you choose.'],['03','JOIN','Join the list. No payment yet.'],['04','WE MAKE IT','When enough people want it, we prepare the batch.'],['05','RESERVE','You get first access when reservations open.'],['06','MEET','Collect at ASTRELI Night or choose delivery.']].map(item=><article key={item[0]}><b>{item[0]}</b><h3>{item[1]}</h3><p>{item[2]}</p></article>)}</div></section>
 <section className="night-invite"><div className="night-image"><Image src="/images/astreli-night-gallery.jpg" fill sizes="(max-width: 800px) 100vw, 55vw" alt="Friends discovering jewellery at ASTRELI Night"/></div><div><small>NEXT ASTRELI NIGHT</small><h2>{nextNight.city}<br/><em>{nextNight.date}</em></h2><p>{nextNight.venue}</p><blockquote>Collect your piece. Discover the next Drop. Bring someone.</blockquote><Link href="/astreli-night">JOIN ASTRELI NIGHT <ArrowRight/></Link><button onClick={invite}><Share2/> BRING SOMEONE WITH YOU</button></div></section>
 <section id="worn" className="worn"><header><small>THE PEOPLE, THE PIECES, THE NIGHT</small><h2>WORN BY ASTRELI</h2></header><div className="social-reel"><figure><Image src="/images/astreli-pdp-model.jpg" fill sizes="40vw" alt="ASTRELI colourful jewellery styling"/><figcaption>DINNER, THEN DIAMONDS.</figcaption></figure><figure className="tall"><Image src="/images/astreli-lifestyle.png" fill sizes="40vw" alt="ASTRELI wearing colourful jewellery"/><figcaption>COLOUR POP · 23:14</figcaption></figure><figure><Image src="/images/astreli-night-gallery.jpg" fill sizes="40vw" alt="Friends at ASTRELI Night"/><figcaption><Play/> SEEN AT ASTRELI NIGHT</figcaption></figure></div></section>
 <section className="previous-night"><div><small>PREVIOUS ASTRELI NIGHT</small><h2>YOU HAD<br/>TO BE THERE.</h2><p>Pieces collected, the next Drop discovered and new people brought into ASTRELI.</p><Link href="/astreli-night#previous">SEE THE NIGHT <ArrowRight/></Link></div><div className="previous-collage"><Image src="/images/astreli-night-gallery.jpg" fill sizes="55vw" alt="Previous ASTRELI Night in Kuala Lumpur"/></div></section>
 <section className="talk-end"><small>STILL DECIDING?</small><h2>LET’S FIND<br/>YOUR PIECE.</h2><button onClick={()=>openStylist()}>FIND MY PIECE <ArrowRight/></button></section>
 </main><footer className="social-footer"><Link className="social-logo" href="/">ASTRELI<span>LABS IN SILVER</span></Link><nav><Link href="#drop">Current Drop</Link><Link href="/custom-made">Custom Made</Link><Link href="/astreli-night">ASTRELI Night</Link><Link href="/contact">Contact</Link><Link href="/materials">Materials</Link><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></nav><p>© 2026 ASTRELI · KUALA LUMPUR</p></footer></>}
