'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import Image from 'next/image';
import Link from 'next/link';
import {ArrowLeft,Check,ChevronLeft,ChevronRight,Diamond,Heart,Instagram,Minus,PackageCheck,Plus,Search,ShieldCheck,ShoppingBag,Sparkles,UserRound,X} from 'lucide-react';
import {collections,products,Product} from '@/data/catalog';

type CartItem={product:Product;qty:number;size?:string};
const money=(n:number)=>`€${n.toLocaleString('en')}`;
function ProductArt({index,className='',sheet}:{index:number;className?:string;sheet?:'electric'}){return <div className={`product-art ${sheet==='electric'?'electric-art':''} ${className}`} role="img" aria-label="Studio photograph of colourful diamond jewellery" style={{backgroundPosition:`${(index%4)*33.333}% ${sheet==='electric'?Math.floor(index/4)*100:Math.floor(index/4)*50}%`}}/>}

export default function Storefront(){
 const [collection,setCollection]=useState(1),[quick,setQuick]=useState<Product|null>(null),[search,setSearch]=useState(false),[query,setQuery]=useState(''),[cartOpen,setCartOpen]=useState(false),[cart,setCart]=useState<CartItem[]>([]),[wish,setWish]=useState<number[]>([]),[size,setSize]=useState('52'),[qty,setQty]=useState(1),[notice,setNotice]=useState('');
 const rail=useRef<HTMLDivElement>(null);
 useEffect(()=>{try{setCart(JSON.parse(localStorage.getItem('astreli-cart')||'[]'))}catch{}},[]);
 useEffect(()=>{localStorage.setItem('astreli-cart',JSON.stringify(cart))},[cart]);
 useEffect(()=>{document.body.style.overflow=(quick||search||cartOpen)?'hidden':'';return()=>{document.body.style.overflow=''}},[quick,search,cartOpen]);
 const selected=collections[collection];
 const results=useMemo(()=>{const q=query.toLowerCase().trim();if(!q)return products.slice(0,6);return products.filter(p=>`${p.name} ${p.metal} ${p.color} ${collections.filter(c=>c.ids.includes(p.id)).map(c=>c.name).join(' ')}`.toLowerCase().includes(q))},[query]);
 const count=cart.reduce((s,i)=>s+i.qty,0), subtotal=cart.reduce((s,i)=>s+i.product.price*i.qty,0);
 const add=(p:Product)=>{setCart(c=>{const i=c.findIndex(x=>x.product.id===p.id&&x.size===(p.kind==='Ring'?size:undefined));if(i<0)return[...c,{product:p,qty,size:p.kind==='Ring'?size:undefined}];return c.map((x,n)=>n===i?{...x,qty:x.qty+qty}:x)});setQuick(null);setQty(1);setCartOpen(true)};
 const update=(i:number,d:number)=>setCart(c=>c.map((x,n)=>n===i?{...x,qty:Math.max(1,x.qty+d)}:x));
 return <>
  <a className="skip" href="#main">Skip to content</a>
  <div className="announcement">Complimentary delivery &amp; returns</div>
  <header className="header"><a className="brand" href="#"><b>ASTRELI</b><span>LAB-GROWN DIAMONDS</span></a><a className="collections-link" href="#collections">COLLECTIONS</a><nav aria-label="Utility navigation"><button aria-label="Search" onClick={()=>setSearch(true)}><Search/></button><button className="account" aria-label="Account"><UserRound/></button><button aria-label={`Shopping bag with ${count} items`} onClick={()=>setCartOpen(true)}><ShoppingBag/>{count>0&&<i>{count}</i>}</button></nav></header>
  <main id="main">
   <section className="intro"><div className="intro-copy"><p>THE EVERYDAY DIAMOND</p><h1>DIAMONDS, MADE<br/>TO COLLECT.</h1><span>Real lab-grown diamonds. Designed for every day.</span></div><div className="hero-image"><Image src="/images/astreli-hero-editorial.jpg" fill priority sizes="(max-width: 700px) 100vw, 56vw" alt="Colourful lab-grown diamond jewellery in sterling silver and gold-plated sterling silver"/></div></section>
   <section id="collections" className="collection-browser"><div className="section-top"><div><small>CURATED, NEVER CROWDED</small><h2>Browse collections</h2></div><div className="rail-controls"><button aria-label="Previous collections" onClick={()=>rail.current?.scrollBy({left:-400,behavior:'smooth'})}><ChevronLeft/></button><button aria-label="Next collections" onClick={()=>rail.current?.scrollBy({left:400,behavior:'smooth'})}><ChevronRight/></button></div></div>
    <div className="collection-rail" ref={rail}>{collections.map((c,i)=>{const cover=products.find(product=>product.id===c.cover)!;return <button key={c.name} onClick={()=>setCollection(i)} className={i===collection?'active':''}><ProductArt index={cover.sprite} sheet={cover.sheet}/><span>{c.name}</span><small>{String(c.ids.length).padStart(2,'0')} PIECES</small></button>})}</div>
   </section>
   <section className="products"><div className="collection-title"><small>THE COLLECTION</small><h2>{selected.name.toUpperCase()}</h2><p>{selected.desc}</p></div><div className="product-grid">{selected.ids.map((id)=>{const p=products.find(x=>x.id===id)!;return <article className="product-card" key={p.id}><button className="product-click" onClick={()=>{setQuick(p);setQty(1)}} aria-label={`View ${p.name}`}><div className="media">{p.badge&&<span className="badge">{p.badge}</span>}<ProductArt index={p.sprite} sheet={p.sheet}/></div><div className="product-info"><h3>{p.name}</h3><p>{p.carat} · {p.metal}</p><strong>{money(p.price)}</strong></div></button><button className={`wish ${wish.includes(p.id)?'saved':''}`} aria-label={`${wish.includes(p.id)?'Remove':'Add'} ${p.name} ${wish.includes(p.id)?'from':'to'} wishlist`} onClick={()=>setWish(w=>w.includes(p.id)?w.filter(x=>x!==p.id):[...w,p.id])}><Heart/></button></article>})}</div></section>
   <section className="about"><div className="about-copy"><small>ABOUT ASTRELI</small><h2>DIAMONDS SHOULDN’T WAIT FOR SPECIAL OCCASIONS.</h2><p>ASTRELI creates small, carefully considered collections of lab-grown diamond jewellery designed to be worn, combined and collected.</p><p>Each collection contains no more than twelve pieces. From playful colour to timeless forms, every design brings genuine diamond brilliance into everyday life.</p><strong>Real diamonds. New possibilities. Made to collect.</strong></div><div className="lifestyle"><Image src="/images/astreli-lifestyle.png" fill sizes="(max-width: 800px) 100vw, 50vw" alt="Woman wearing colourful ASTRELI-style diamond jewellery"/></div></section>
   <section className="promise"><small>THE ASTRELI PROMISE</small><div><article><Diamond/><h3>GENUINE LAB-GROWN DIAMONDS</h3><p>Real diamonds with the same optical, physical and chemical properties as mined diamonds.</p></article><article><Sparkles/><h3>DESIGNED IN SMALL COLLECTIONS</h3><p>No overwhelming catalogue—just distinctive, considered designs.</p></article><article><PackageCheck/><h3>MADE FOR EVERY DAY</h3><p>Jewellery created to wear, combine, gift and collect.</p></article></div></section>
   <section className="newsletter"><div><small>THE ASTRELI LETTER</small><h2>BE FIRST TO DISCOVER<br/>THE NEXT COLLECTION.</h2><p>New collections. Limited designs. A little more brilliance in your inbox.</p></div><form onSubmit={e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const email=String(fd.get('email'));setNotice(/^\S+@\S+\.\S+$/.test(email)?'Thank you — you’re on the list.':'Please enter a valid email address.')}} noValidate><label htmlFor="email">Email address</label><div><input id="email" name="email" type="email" placeholder="Your email address" aria-describedby="newsletter-notice"/><button>JOIN THE LIST</button></div><p id="newsletter-notice" role="status">{notice}</p></form></section>
  </main>
  <footer><a className="brand footer-brand" href="#"><b>ASTRELI</b><span>LAB-GROWN DIAMONDS</span></a><div className="footer-links"><Link href="/delivery-returns">Delivery &amp; Returns</Link><Link href="/warranty">Warranty</Link><Link href="/materials">Materials</Link><Link href="/contact">Contact</Link><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></div><div className="footer-bottom"><span>© 2026 ASTRELI</span><a href="#" aria-label="Instagram"><Instagram/></a></div></footer>
  {search&&<div className="overlay" role="dialog" aria-modal="true" aria-label="Search"><div className="search-panel"><div className="overlay-head"><h2>Search ASTRELI</h2><button aria-label="Close search" onClick={()=>setSearch(false)}><X/></button></div><label className="search-box"><Search/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search pieces, metals or colours"/><span>{results.length} results</span></label><div className="search-results">{results.map(p=><button key={p.id} onClick={()=>{setSearch(false);setQuick(p)}}><ProductArt index={p.sprite} sheet={p.sheet}/><span><b>{p.name}</b><small>{p.metal}</small><em>{money(p.price)}</em></span></button>)}</div></div></div>}
  {quick&&<div className="overlay quick-wrap" role="dialog" aria-modal="true" aria-labelledby="quick-title"><div className="quick quick-pdp"><button className="close" aria-label="Close quick view" onClick={()=>setQuick(null)}><X/></button><div className="quick-gallery"><div className="gallery-product"><ProductArt index={quick.sprite} sheet={quick.sheet}/><span>THE PIECE</span></div><div className={`gallery-model ${quick.kind.toLowerCase()}`}><Image src={`/images/models/${quick.id}.jpg`} fill sizes="(max-width: 600px) 100vw, 36vw" alt={`Model wearing the ${quick.name}`}/><span>WORN BY ASTRELI</span></div><div className="gallery-detail"><Image src="/images/astreli-materials-detail.jpg" fill sizes="(max-width: 600px) 50vw, 18vw" alt="Lab-grown diamonds beside genuine 925 sterling silver and jewellery-setting tools"/><span>LAB DIAMONDS · 925 SILVER</span></div></div><div className="quick-copy"><button className="back" onClick={()=>setQuick(null)}><ArrowLeft/> BACK TO COLLECTION</button><div className="pdp-kicker"><small>{quick.badge||'ASTRELI COLLECTION'}</small><span><i/> IN STOCK</span></div><h2 id="quick-title">{quick.name}</h2><strong>{money(quick.price)}</strong><p className="meta">{quick.carat} lab-grown diamond · {quick.metal}</p><div className="pdp-story"><h3>WHY YOU’LL LOVE IT</h3><p>{quick.description}</p><ul><li><Diamond/>Genuine lab-grown diamond brilliance</li><li><Sparkles/>Designed to wear alone or layer</li><li><ShieldCheck/>Two-year manufacturing warranty</li></ul></div>{quick.kind==='Ring'&&<fieldset><legend>SELECT RING SIZE <Link href="/contact">SIZE HELP</Link></legend><div>{['48','50','52','54','56'].map(s=><button className={s===size?'on':''} key={s} onClick={()=>setSize(s)}>{s}</button>)}</div></fieldset>}<div className="buy-row"><div className="qty"><button aria-label="Decrease quantity" onClick={()=>setQty(Math.max(1,qty-1))}><Minus/></button><span>{qty}</span><button aria-label="Increase quantity" onClick={()=>setQty(qty+1)}><Plus/></button></div><button className="add" onClick={()=>add(quick)}>ADD TO BAG — {money(quick.price*qty)}</button></div><div className="pdp-assurance"><p><PackageCheck/> Complimentary insured delivery &amp; 30-day returns</p><p><Check/> Presented in signature ASTRELI packaging</p></div><nav className="product-care" aria-label="Product care information"><Link href="/delivery-returns">Delivery &amp; returns</Link><Link href="/warranty">Warranty</Link><Link href="/materials">Materials &amp; care</Link></nav></div></div></div>}
  {cartOpen&&<div className="overlay drawer-wrap" role="dialog" aria-modal="true" aria-labelledby="cart-title" onMouseDown={e=>{if(e.target===e.currentTarget)setCartOpen(false)}}><aside className="cart"><div className="overlay-head"><h2 id="cart-title">Your bag <sup>{count}</sup></h2><button aria-label="Close bag" onClick={()=>setCartOpen(false)}><X/></button></div>{cart.length===0?<div className="empty"><ShoppingBag/><h3>Your bag is waiting.</h3><p>Discover a piece made for every day.</p><button onClick={()=>setCartOpen(false)}>BROWSE COLLECTIONS</button></div>:<><div className="cart-items">{cart.map((item,i)=><article key={`${item.product.id}-${item.size}`}><ProductArt index={item.product.sprite} sheet={item.product.sheet}/><div><h3>{item.product.name}</h3><p>{item.product.metal}{item.size?` · Size ${item.size}`:''}</p><strong>{money(item.product.price)}</strong><div className="cart-actions"><div className="qty"><button aria-label="Decrease quantity" onClick={()=>update(i,-1)}><Minus/></button><span>{item.qty}</span><button aria-label="Increase quantity" onClick={()=>update(i,1)}><Plus/></button></div><button className="remove" onClick={()=>setCart(c=>c.filter((_,n)=>n!==i))}>Remove</button></div></div></article>)}</div><div className="cart-total"><div><span>Subtotal</span><strong>{money(subtotal)}</strong></div><p>Delivery is complimentary. Taxes calculated at checkout.</p><button>PROTOTYPE CHECKOUT</button><small>Preview only — no payment will be taken.</small></div></>}</aside></div>}
 </>;
}
