'use client';
import Image from 'next/image';import Link from 'next/link';import {ArrowDownRight,ArrowRight} from 'lucide-react';
import {currentDrop,featuredProducts,socialPrice} from '@/data/social-commerce';import {Product,productSlug} from '@/data/catalog';import {useStylist} from './StylistProvider';import SocialHeader from './SocialHeader';import {track} from '@/lib/social-analytics';
const money=(value:number)=>`RM ${value.toLocaleString('en')}`;function ProductVisual({product}:{product:Product}){return <div className="social-product-visual"><Image src={`/images/models/${product.id}.jpg`} fill sizes="(max-width: 700px) 100vw, 52vw" alt={`ASTRELI wearing ${product.name}`}/></div>}
export default function Storefront(){const {openStylist}=useStylist();return <><div className="social-announcement">DROP 01 · COLOUR POP · WAITLIST OPEN</div><SocialHeader/><main className="social-home waitlist-home">
 <section className="social-hero"><Image src="/images/social-hero.jpg" fill priority sizes="100vw" alt="ASTRELI and friends wearing ASTRELI lab-grown diamond jewellery in Kuala Lumpur"/><div className="social-hero-shade"/><div className="social-hero-copy"><small>YOUR PERSONAL JEWELLERY STYLIST</small><h1>FIND YOUR<br/>PIECE.<br/><em>WE’LL TAKE IT<br/>FROM THERE.</em></h1><p>A small edit, chosen with you and made in batches. Join the list for anything you love — we’ll tell you when the next batch is ready.</p><div><button onClick={()=>{track('hero_cta_click',{cta:'find_my_piece'});openStylist()}}>FIND MY PIECE <ArrowRight/></button><a href="#drop">EXPLORE THE DROP <ArrowDownRight/></a></div></div><span className="hero-side">THE DROP · FIND MY PIECE · MADE IN DROPS</span></section>
 <section id="drop" className="drop-intro"><div><small>CURRENT DROP · NEXT BATCH FORMING</small><h2>COLOUR<br/>POP</h2></div><p>{currentDrop.line}<br/><span>{currentDrop.description}</span></p></section>
 <section className="made-in-drops"><small>MADE IN DROPS</small><h2>WE MAKE ASTRELI<br/>IN SMALL BATCHES.</h2><p>Join the list for a piece you love. When enough people want it, we make the next batch — and you get first access.</p><div><span>NO PAYMENT WHEN YOU JOIN</span><a href="#pieces">EXPLORE THE DROP <ArrowRight/></a></div></section>
 <section id="pieces" className="editorial-products waitlist-products">{featuredProducts.map((product,index)=><article className={index%2?'reverse':''} key={product.id}><ProductVisual product={product}/><div><small>NEXT BATCH FORMING · 0{index+1}</small><h3>{product.name}</h3><strong>{money(socialPrice(product))}</strong><p>{product.description}</p><span>NO PAYMENT YET · FIRST ACCESS WHEN THE BATCH OPENS<br/>{product.carat} · {product.metal}</span><Link href={`/products/${productSlug(product)}`}>SEE THE PIECE <ArrowRight/></Link><button onClick={()=>{track('join_list_clicked',{product:product.name,status:'batch_forming'});openStylist({product,mode:'waitlist'})}}>JOIN THE LIST <ArrowRight/></button></div></article>)}</section>
 <div className="full-drop-link"><Link href="/drop">EXPLORE ALL 8 PIECES <ArrowRight/></Link></div><section className="stylist-feature"><div><small>YOUR ASTRELI STYLIST</small><h2>NOT SURE<br/>WHERE TO START?</h2><p>Tell us what you like, where you’ll wear it and what feels comfortable. Your stylist will show you two or three pieces worth seeing — not twenty.</p><button onClick={()=>openStylist()}>FIND MY PIECE <ArrowRight/></button></div><div className="stylist-feature-image"><Image src="/images/astreli-pdp-model.jpg" fill sizes="(max-width: 800px) 100vw, 50vw" alt="ASTRELI personal jewellery stylist edit"/></div></section>
 <section className="shape-next"><small>YOU HELP SHAPE WHAT COMES NEXT</small><h2>LOTS FOR ASTRELI<br/>TO CHOOSE FROM.<br/><em>THREE FOR YOU.</em></h2><p>Your stylist can show you designs from our wider private library. Your favourites help ASTRELI curate what enters the next Drop.</p><button onClick={()=>openStylist()}>FIND MY PIECE <ArrowRight/></button></section><section id="how" className="how"><header><small>CURATED BY ASTRELI, INFORMED BY YOU</small><h2>HOW ASTRELI WORKS</h2></header><div>{[['01','DISCOVER','Explore the current Drop.'],['02','FIND','Or let your stylist find it.'],['03','JOIN','Tell us which piece you want. No payment yet.'],['04','WE CURATE','Your interest helps shape what we make next.'],['05','RESERVE','When your batch opens, you get first access.'],['06','WE MAKE IT','We prepare the batch and arrange delivery when it is ready.']].map(item=><article key={item[0]}><b>{item[0]}</b><h3>{item[1]}</h3><p>{item[2]}</p></article>)}</div></section>

 <section id="worn" className="worn"><header><small>THE MUSE, THE PIECES, THE STYLING</small><h2>WORN BY ASTRELI</h2></header><div className="social-reel"><figure><Image src="/images/astreli-pdp-model.jpg" fill sizes="40vw" alt="ASTRELI colourful jewellery styling"/><figcaption>DINNER, THEN DIAMONDS.</figcaption></figure><figure className="tall"><Image src="/images/astreli-lifestyle.png" fill sizes="40vw" alt="ASTRELI wearing colourful jewellery"/><figcaption>COLOUR POP · 23:14</figcaption></figure></div></section>

 <section className="talk-end"><small>STILL DECIDING?</small><h2>LET’S FIND<br/>YOUR PIECE.</h2><button onClick={()=>openStylist()}>FIND MY PIECE <ArrowRight/></button></section>
 </main><footer className="social-footer"><Link className="social-logo" href="/">ASTRELI<span>LABS IN SILVER</span></Link><nav><Link href="/drop">Current Drop</Link><Link href="/contact">Contact</Link><Link href="/materials">Materials</Link><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></nav><p>© 2026 ASTRELI · KUALA LUMPUR</p></footer></>}
