'use client';
import {createContext,useContext,useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {ArrowRight,ArrowUp,MessageCircle,UserRound,X} from 'lucide-react';
import {Product,productSlug} from '@/data/catalog';
import {currentDrop,LeadRecord} from '@/data/social-commerce';
import {Design,recommendDesigns,recommendationReason} from '@/data/design-library';
import {leadRepository} from '@/lib/lead-repository';
import {track} from '@/lib/social-analytics';

type Message={from:'astreli'|'you';text:string};type Mode='discover'|'product'|'waitlist';type Stage='welcome'|'category'|'mood'|'occasion'|'budget'|'metal'|'recommendations'|'product_actions'|'size'|'finish'|'name'|'whatsapp'|'email'|'done';
type Context={openStylist:(options?:{product?:Product;mode?:Mode})=>void};
const StylistContext=createContext<Context>({openStylist:()=>{}});export const useStylist=()=>useContext(StylistContext);
const makeLead=(product?:Product):LeadRecord=>{const query=typeof window==='undefined'?new URLSearchParams():new URLSearchParams(location.search);return{timestamp:new Date().toISOString(),sessionId:crypto.randomUUID(),source:query.get('utm_source')||document.referrer||'direct',campaign:query.get('utm_campaign')||undefined,utm:Object.fromEntries([...query.entries()].filter(([key])=>key.startsWith('utm_'))),landingPage:location.pathname,productViewed:product?.name,productId:product?.id,conversationStarted:true,productInterest:product?.name,drop:`Drop ${currentDrop.number} · ${currentDrop.name}`,waitlistStatus:'not_joined',reservationStatus:'not_started',depositStatus:'not_started',conversationStatus:'conversation_started',transcript:[]}};
const prompt:Record<string,string>={category:'What are we finding — a ring, earrings, necklace or bracelet?',mood:'Which direction feels most like you?',occasion:'Where do you imagine wearing it?',budget:'What price range feels comfortable?'};

export default function StylistProvider({children}:{children:React.ReactNode}){
 const [open,setOpen]=useState(false),[product,setProduct]=useState<Product>(),[messages,setMessages]=useState<Message[]>([]),[stage,setStage]=useState<Stage>('welcome'),[lead,setLead]=useState<LeadRecord>(),[text,setText]=useState(''),[picks,setPicks]=useState<Design[]>([]),[recommendationPage,setRecommendationPage]=useState(0);
 useEffect(()=>{if(lead)leadRepository.save({...lead,transcript:messages.map(item=>`${item.from}: ${item.text}`)})},[lead,messages]);
 const openStylist=({product:item,mode=item?'product':'discover'}:{product?:Product;mode?:Mode}={})=>{const next=makeLead(item);setProduct(item);setLead(next);setOpen(true);setPicks([]);track('stylist_opened',{mode,product:item?.name});track('conversation_started',{mode,product:item?.name});if(item){setStage(mode==='waitlist'?'size':'product_actions');setMessages([{from:'astreli',text:mode==='waitlist'?`Absolutely ✨ I can put you on the list for the ${item.name}. The next batch is forming now. ${item.kind==='Ring'?'What size are you looking for?':'Would you prefer silver or gold tone?'}`:`Good choice ✨ You’re looking at the ${item.name}. The next batch is currently forming. Want to join the list, check sizing or compare alternatives?`}]);if(mode==='waitlist'){setLead({...next,waitlistStatus:'collecting_preferences',conversationStatus:'qualified_lead'});track('waitlist_conversation_started',{product:item.name})}}else{setStage('category');setMessages([{from:'astreli',text:'Let’s find your ASTRELI piece. I’ll ask four quick questions, then show you only a few worth seeing.'},{from:'astreli',text:prompt.category}])}};
 const say=(choice:string)=>setMessages(items=>[...items,{from:'you',text:choice}]);
 const recommend=(current:LeadRecord,page=0)=>{const preferences={category:current.category,style:current.stylePreference,occasion:current.occasion,budget:current.budget,metal:current.preferredFinish};const selection=recommendDesigns(preferences,page*3);setPicks(selection);setRecommendationPage(page);setLead({...current,recommendedProducts:selection.map(item=>item.product.name)});setStage('recommendations');setMessages(items=>[...items,{from:'astreli',text:'I think these three are closest to what you’re describing. I kept the edit small.'}]);track('recommendation_shown',{products:selection.map(item=>item.product.name)})};
 const choose=(value:string)=>{say(value);if(stage==='category'){setLead(current=>current?{...current,category:value}:current);setStage('mood');setMessages(items=>[...items,{from:'astreli',text:prompt.mood}])}else if(stage==='mood'){setLead(current=>current?{...current,stylePreference:value}:current);setStage('occasion');setMessages(items=>[...items,{from:'astreli',text:prompt.occasion}])}else if(stage==='occasion'){setLead(current=>current?{...current,occasion:value}:current);setStage('budget');setMessages(items=>[...items,{from:'astreli',text:prompt.budget}])}else if(stage==='budget'){setLead(current=>current?{...current,budget:value}:current);setStage('metal');setMessages(items=>[...items,{from:'astreli',text:'Silver or gold tone?'}])}else if(stage==='metal'){const next={...lead!,preferredFinish:value,conversationStatus:'qualified_lead' as const};setLead(next);recommend(next)}else if(stage==='product_actions'){if(value==='I want this one')beginWaitlist();else if(value==='Talk to a person')human();else if(value==='What does Join the List mean?'){track('waitlist_question',{product:product?.name});track('waitlist_explanation_viewed',{product:product?.name});setMessages(items=>[...items,{from:'astreli',text:'ASTRELI pieces are made in small batches. Joining the list tells us you want this piece. There is no payment yet. When the next batch is ready, you will get first access to reserve yours.'},{from:'astreli',text:'Want me to add you to the list?'}])}else setMessages(items=>[...items,{from:'astreli',text:value==='Help with sizing'?'I can help. Rings use EU sizing; tell me a ring that already fits or choose size help when joining the list.':value==='Show me similar'?'I’ll compare colour, shape and how noticeable it feels — never an endless list.':value==='Can I change something?'?'Usually we can discuss finish and selected details before the Drop is confirmed. Tell me what you have in mind.':value==='When can I get it?'?`When your batch opens, you get first access to reserve. Once it is ready, we’ll arrange delivery with you.`:'Of course. Ask me anything about the piece.'}])}else if(stage==='size'){setLead(current=>current?{...current,ringSize:value,waitlistStatus:'collecting_preferences'}:current);track('waitlist_preference',{size:value});setStage('finish');setMessages(items=>[...items,{from:'astreli',text:'And which finish feels right?'}])}else if(stage==='finish'){setLead(current=>current?{...current,preferredFinish:value,variation:value}:current);track('waitlist_preference',{finish:value});setStage('name');setMessages(items=>[...items,{from:'astreli',text:`Perfect. I can put you on the list for the September Drop. What should I call you?`}])}};
 const beginInterest=(design:Design)=>{const item=design.product,isWaitlist=design.currentDrop;setProduct(item);setLead(current=>current?{...current,productId:item.id,productInterest:item.name,interestType:isWaitlist?'product_waitlist':'design_interest',waitlistStatus:'collecting_preferences',conversationStatus:'qualified_lead'}:{...makeLead(item),interestType:isWaitlist?'product_waitlist':'design_interest'});track('recommendation_selected',{product:item.name,currentDrop:isWaitlist});setStage(item.kind==='Ring'?'size':'finish');setMessages(items=>[...items,{from:'you',text:`I like the ${item.name}`},{from:'astreli',text:isWaitlist?`Beautiful choice. This piece is in the current Drop. ${item.kind==='Ring'?'What size are you looking for?':'Would you prefer silver or gold tone?'}`:`This one isn’t in the current Drop, but I can add your interest for a future one. Your interest helps ASTRELI decide what comes next — it does not promise a one-off piece. ${item.kind==='Ring'?'What size would you want?':'Would you prefer silver or gold tone?'}`}])};
 const beginWaitlist=(item=product)=>{if(!item)return;const design=recommendDesigns({}).find(entry=>entry.product.id===item.id);if(design)beginInterest(design)};
 const showAnother=()=>{const nextPage=(recommendationPage+1)%7;track('show_another_clicked',{page:nextPage});setLead(current=>current?{...current,rejectedProducts:[...(current.rejectedProducts||[]),...picks.map(item=>item.product.name)]}:current);if(lead)recommend(lead,nextPage)};
 const human=()=>{setLead(current=>current?{...current,conversationStatus:'human_requested'}:current);setStage('name');setMessages(items=>[...items,{from:'you',text:'Talk to a person'},{from:'astreli',text:'Of course. What should I call you? A human stylist will receive our full conversation.'}]);track('human_handoff',{product:product?.name})};
 const send=()=>{if(!text.trim())return;const value=text.trim();setText('');say(value);if(stage==='name'){setLead(current=>current?{...current,name:value}:current);setStage('whatsapp');setMessages(items=>[...items,{from:'astreli',text:`Lovely to meet you, ${value}. What’s the best WhatsApp number for Drop updates?`}])}else if(stage==='whatsapp'){setLead(current=>current?{...current,whatsapp:value}:current);setStage('email');setMessages(items=>[...items,{from:'astreli',text:'And an email address as a quiet backup? You can type “skip” if you prefer WhatsApp only.'}])}else if(stage==='email'){const designInterest=lead?.interestType==='design_interest';const joined={...lead!,email:value.toLowerCase()==='skip'?undefined:value,waitlistStatus:'joined' as const,conversationStatus:(designInterest?'design_interest_added':'joined_waitlist') as LeadRecord['conversationStatus']};setLead(joined);setStage('done');setMessages(items=>[...items,{from:'astreli',text:designInterest?`I’ve added your interest ✨ This design isn’t in the current Drop. If ASTRELI selects it for a future one, you’ll hear first. There’s nothing to pay.`:`You’re on the list ✨ There’s nothing to pay yet. We’ll let you know first when the next batch is ready to reserve.`}]);track('lead_captured',{product:product?.name});track(designInterest?'design_interest_added':'product_waitlist_joined',{product:product?.name,size:joined.ringSize,finish:joined.preferredFinish})}else setMessages(items=>[...items,{from:'astreli',text:'I’ve noted that. I can help you choose, compare, join a Drop or bring in a human stylist.'}])};
 const options=useMemo(()=>stage==='category'?['Ring','Earrings','Necklace','Bracelet','Surprise me']:stage==='mood'?['Colourful','Minimal','Classic','Statement','Everyday']:stage==='occasion'?['Every day','Dinner & events','A gift']:stage==='budget'?['Up to RM 700','Up to RM 1,000','Up to RM 1,500']:stage==='metal'?['Silver','Gold tone']:stage==='product_actions'?['I want this one','Help with sizing','Show me similar','When can I get it?','What does Join the List mean?','Talk to a person']:stage==='size'?['48','50','52','54','56','I need help']:stage==='finish'?['Sterling silver','Gold tone','Help me decide']:[] ,[stage]);
 return <StylistContext.Provider value={{openStylist}}>{children}<button className="stylist-fab" onClick={()=>openStylist()} aria-label="Find my piece"><MessageCircle/><span>FIND MY PIECE</span></button>{open&&<aside className="stylist" aria-label="Your ASTRELI Stylist" aria-live="polite"><header><div><i>AI</i><span><b>Your ASTRELI Stylist</b><small>Personal edit · Human whenever you want one</small></span></div><button onClick={()=>setOpen(false)} aria-label="Close stylist"><X/></button></header>{product&&<Link className="stylist-product" href={`/products/${productSlug(product)}`}><span>{product.name}</span><small>Next Drop · September</small></Link>}<div className="stylist-messages">{messages.map((message,index)=><p className={message.from} key={index}>{message.text}</p>)}{stage==='recommendations'&&<div className="stylist-recommendations">{picks.map(design=><article key={design.product.id}><Link href={"/products/"+design.slug}><span>{design.product.name}</span><small>{design.product.metal} · RM {design.price.toLocaleString('en')}</small><em>{recommendationReason(design,{category:lead?.category,style:lead?.stylePreference,occasion:lead?.occasion,budget:lead?.budget,metal:lead?.preferredFinish})}</em></Link><button onClick={()=>beginInterest(design)}>{design.currentDrop?'I LIKE THIS':'ADD MY INTEREST'} <ArrowRight/></button></article>)} </div>}</div><div className="stylist-actions">{options.map(label=><button key={label} onClick={()=>choose(label)}>{label}</button>)}{stage==='recommendations'&&<><button onClick={showAnother}>Show me another</button><button onClick={human}>Talk to a person</button></>}</div><form onSubmit={event=>{event.preventDefault();send()}}><input value={text} onChange={event=>setText(event.target.value)} placeholder={stage==='name'?'Your first name':stage==='whatsapp'?'WhatsApp with country code':stage==='email'?'Email or “skip”':'Ask your stylist anything…'}/><button aria-label="Send"><ArrowUp/></button></form><footer><UserRound/> Human whenever you want one</footer></aside>}</StylistContext.Provider>;
}
