'use client';
import {createContext,useContext,useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {ArrowRight,ArrowUp,MessageCircle,UserRound,X} from 'lucide-react';
import {products,Product,productSlug} from '@/data/catalog';
import {currentDrop,LeadRecord,nextNight,socialPrice} from '@/data/social-commerce';
import {leadRepository} from '@/lib/lead-repository';
import {track} from '@/lib/social-analytics';

type Message={from:'astreli'|'you';text:string};type Mode='discover'|'product'|'waitlist';type Stage='welcome'|'category'|'mood'|'occasion'|'budget'|'recommendations'|'product_actions'|'size'|'finish'|'name'|'whatsapp'|'email'|'done';
type Context={openStylist:(options?:{product?:Product;mode?:Mode})=>void};
const StylistContext=createContext<Context>({openStylist:()=>{}});export const useStylist=()=>useContext(StylistContext);
const makeLead=(product?:Product):LeadRecord=>{const query=typeof window==='undefined'?new URLSearchParams():new URLSearchParams(location.search);return{timestamp:new Date().toISOString(),sessionId:crypto.randomUUID(),source:query.get('utm_source')||document.referrer||'direct',campaign:query.get('utm_campaign')||undefined,utm:Object.fromEntries([...query.entries()].filter(([key])=>key.startsWith('utm_'))),landingPage:location.pathname,productViewed:product?.name,productId:product?.id,conversationStarted:true,productInterest:product?.name,drop:`Drop ${currentDrop.number} · ${currentDrop.name}`,waitlistStatus:'not_joined',reservationStatus:'not_started',depositStatus:'not_started',conversationStatus:'conversation_started',transcript:[]}};
const prompt:Record<string,string>={category:'What are we finding — a ring, earrings, necklace or bracelet?',mood:'Which direction feels most like you?',occasion:'Where do you imagine wearing it?',budget:'What price range feels comfortable?'};

export default function StylistProvider({children}:{children:React.ReactNode}){
 const [open,setOpen]=useState(false),[product,setProduct]=useState<Product>(),[messages,setMessages]=useState<Message[]>([]),[stage,setStage]=useState<Stage>('welcome'),[lead,setLead]=useState<LeadRecord>(),[text,setText]=useState(''),[picks,setPicks]=useState<Product[]>([]);
 useEffect(()=>{if(lead)leadRepository.save({...lead,transcript:messages.map(item=>`${item.from}: ${item.text}`)})},[lead,messages]);
 const openStylist=({product:item,mode=item?'product':'discover'}:{product?:Product;mode?:Mode}={})=>{const next=makeLead(item);setProduct(item);setLead(next);setOpen(true);setPicks([]);track('stylist_opened',{mode,product:item?.name});track('conversation_started',{mode,product:item?.name});if(item){setStage(mode==='waitlist'?'size':'product_actions');setMessages([{from:'astreli',text:mode==='waitlist'?`Absolutely ✨ I’ll help you join the ${currentDrop.name} list for the ${item.name}. ${item.kind==='Ring'?'What size are you looking for?':'Would you prefer silver or gold tone?'}`:`Good choice ✨ You’re looking at the ${item.name}. Want to check details, compare alternatives, or join the next Drop?`}]);if(mode==='waitlist')setLead({...next,waitlistStatus:'collecting_preferences',conversationStatus:'qualified_lead'})}else{setStage('category');setMessages([{from:'astreli',text:'Let’s find your ASTRELI piece. I’ll ask four quick questions, then show you only a few worth seeing.'},{from:'astreli',text:prompt.category}])}};
 const say=(choice:string)=>setMessages(items=>[...items,{from:'you',text:choice}]);
 const recommend=(current:LeadRecord)=>{const category=current.category||'',mood=current.stylePreference||'',budget=Number((current.budget||'1500').replace(/\D/g,''))||1500;let matches=products.filter(item=>(!category||item.kind.toLowerCase().includes(category.toLowerCase()))&&socialPrice(item)<=budget);if(/colour/i.test(mood))matches=matches.filter(item=>item.color!=='White');if(/minimal/i.test(mood))matches=matches.filter(item=>item.color==='White');const selection=(matches.length?matches:products).slice(0,3);setPicks(selection);setStage('recommendations');setMessages(items=>[...items,{from:'astreli',text:`I found ${selection.length} pieces that fit. I kept the edit small — start with the one that gives you an immediate feeling.`}]);track('recommendation_shown',{products:selection.map(item=>item.name)})};
 const choose=(value:string)=>{say(value);if(stage==='category'){setLead(current=>current?{...current,category:value}:current);setStage('mood');setMessages(items=>[...items,{from:'astreli',text:prompt.mood}])}else if(stage==='mood'){setLead(current=>current?{...current,stylePreference:value}:current);setStage('occasion');setMessages(items=>[...items,{from:'astreli',text:prompt.occasion}])}else if(stage==='occasion'){setLead(current=>current?{...current,occasion:value}:current);setStage('budget');setMessages(items=>[...items,{from:'astreli',text:prompt.budget}])}else if(stage==='budget'){const next={...lead!,budget:value,conversationStatus:'qualified_lead' as const};setLead(next);recommend(next)}else if(stage==='product_actions'){if(value==='I want this one')beginWaitlist();else if(value==='Talk to a person')human();else setMessages(items=>[...items,{from:'astreli',text:value==='Help with sizing'?'I can help. Rings use EU sizing; tell me a ring that already fits or choose size help when joining the list.':value==='Show me similar'?'I’ll compare colour, shape and how noticeable it feels — never an endless list.':value==='Can I change something?'?'Usually we can discuss finish and selected details before the Drop is confirmed. Tell me what you have in mind.':value==='When can I get it?'?`The next Drop is prepared for September. Collect at ASTRELI Night on ${nextNight.date} or choose delivery.`:'Of course. Ask me anything about the piece.'}])}else if(stage==='size'){setLead(current=>current?{...current,ringSize:value,waitlistStatus:'collecting_preferences'}:current);track('waitlist_preference',{size:value});setStage('finish');setMessages(items=>[...items,{from:'astreli',text:'And which finish feels right?'}])}else if(stage==='finish'){setLead(current=>current?{...current,preferredFinish:value,variation:value}:current);track('waitlist_preference',{finish:value});setStage('name');setMessages(items=>[...items,{from:'astreli',text:`Perfect. I can put you on the list for the September Drop. What should I call you?`}])}};
 const beginWaitlist=(item=product)=>{if(!item)return;setProduct(item);setLead(current=>current?{...current,productId:item.id,productInterest:item.name,waitlistStatus:'collecting_preferences',conversationStatus:'qualified_lead'}:makeLead(item));track('waitlist_product',{product:item.name});setStage(item.kind==='Ring'?'size':'finish');setMessages(items=>[...items,{from:'you',text:`I’m interested in ${item.name}`},{from:'astreli',text:item.kind==='Ring'?'Beautiful choice. What size are you looking for?':'Beautiful choice. Would you prefer silver or gold tone?'}])};
 const human=()=>{setLead(current=>current?{...current,conversationStatus:'human_requested'}:current);setStage('name');setMessages(items=>[...items,{from:'you',text:'Talk to a person'},{from:'astreli',text:'Of course. What should I call you? A human stylist will receive our full conversation.'}]);track('human_handoff',{product:product?.name})};
 const send=()=>{if(!text.trim())return;const value=text.trim();setText('');say(value);if(stage==='name'){setLead(current=>current?{...current,name:value}:current);setStage('whatsapp');setMessages(items=>[...items,{from:'astreli',text:`Lovely to meet you, ${value}. What’s the best WhatsApp number for Drop updates?`}])}else if(stage==='whatsapp'){setLead(current=>current?{...current,whatsapp:value}:current);setStage('email');setMessages(items=>[...items,{from:'astreli',text:'And an email address as a quiet backup? You can type “skip” if you prefer WhatsApp only.'}])}else if(stage==='email'){const joined={...lead!,email:value.toLowerCase()==='skip'?undefined:value,waitlistStatus:'joined' as const,conversationStatus:'joined_waitlist' as const};setLead(joined);setStage('done');setMessages(items=>[...items,{from:'astreli',text:`You’re on the September Drop list ✨ We’ll contact you personally before reservations open. No payment has been taken.`}]);track('lead_captured',{product:product?.name});track('waitlist_joined',{product:product?.name,size:joined.ringSize,finish:joined.preferredFinish,drop:joined.drop})}else setMessages(items=>[...items,{from:'astreli',text:'I’ve noted that. I can help you choose, compare, personalise, join a Drop or bring in a human stylist.'}])};
 const options=useMemo(()=>stage==='category'?['Ring','Earrings','Necklace','Bracelet']:stage==='mood'?['Colourful','Minimal','A little unexpected']:stage==='occasion'?['Every day','Dinner & events','A gift']:stage==='budget'?['Up to RM 700','Up to RM 1,000','Up to RM 1,500']:stage==='product_actions'?['I want this one','Help with sizing','Show me similar','Can I change something?','When can I get it?','Talk to a person']:stage==='size'?['48','50','52','54','56','I need help']:stage==='finish'?['Sterling silver','Gold tone','Help me decide']:[] ,[stage]);
 return <StylistContext.Provider value={{openStylist}}>{children}<button className="stylist-fab" onClick={()=>openStylist()} aria-label="Find my piece"><MessageCircle/><span>FIND MY PIECE</span></button>{open&&<aside className="stylist" aria-label="Your ASTRELI Stylist" aria-live="polite"><header><div><i>AI</i><span><b>Your ASTRELI Stylist</b><small>Personal edit · Human whenever you want one</small></span></div><button onClick={()=>setOpen(false)} aria-label="Close stylist"><X/></button></header>{product&&<Link className="stylist-product" href={`/products/${productSlug(product)}`}><span>{product.name}</span><small>Next Drop · September</small></Link>}<div className="stylist-messages">{messages.map((message,index)=><p className={message.from} key={index}>{message.text}</p>)}{stage==='recommendations'&&<div className="stylist-recommendations">{picks.map(item=><button key={item.id} onClick={()=>beginWaitlist(item)}><span>{item.name}</span><small>{item.carat} · RM {socialPrice(item).toLocaleString('en')}</small><b>JOIN THE LIST <ArrowRight/></b></button>)}</div>}</div><div className="stylist-actions">{options.map(label=><button key={label} onClick={()=>choose(label)}>{label}</button>)}{stage==='recommendations'&&<button onClick={human}>Talk to a person</button>}</div><form onSubmit={event=>{event.preventDefault();send()}}><input value={text} onChange={event=>setText(event.target.value)} placeholder={stage==='name'?'Your first name':stage==='whatsapp'?'WhatsApp with country code':stage==='email'?'Email or “skip”':'Ask your stylist anything…'}/><button aria-label="Send"><ArrowUp/></button></form><footer><UserRound/> Human whenever you want one</footer></aside>}</StylistContext.Provider>;
}
