'use client';
import {createContext,useContext,useEffect,useState} from 'react';
import Link from 'next/link';
import {ArrowUp,MessageCircle,UserRound,X} from 'lucide-react';
import {products,Product,productSlug} from '@/data/catalog';
import {LeadRecord,nextNight} from '@/data/social-commerce';
import {leadRepository} from '@/lib/lead-repository';
import {track} from '@/lib/social-analytics';

type Message={from:'astreli'|'you';text:string};
type Context={openChat:(product?:Product,action?:string)=>void};
const StylistContext=createContext<Context>({openChat:()=>{}});
export const useStylist=()=>useContext(StylistContext);

function makeLead(product?:Product):LeadRecord{
 const query=typeof window==='undefined'?new URLSearchParams():new URLSearchParams(location.search);
 const utm=Object.fromEntries([...query.entries()].filter(([key])=>key.startsWith('utm_')));
 return {timestamp:new Date().toISOString(),sessionId:crypto.randomUUID(),source:query.get('utm_source')||document.referrer||'direct',campaign:query.get('utm_campaign')||undefined,utm,landingPage:location.pathname,productViewed:product?.name,conversationStarted:true,productInterest:product?.name,depositStatus:'not_started',conversationStatus:'new',transcript:[]};
}
export default function StylistProvider({children}:{children:React.ReactNode}){
 const [open,setOpen]=useState(false),[product,setProduct]=useState<Product>(),[messages,setMessages]=useState<Message[]>([]),[text,setText]=useState(''),[lead,setLead]=useState<LeadRecord>(),[stage,setStage]=useState<'idle'|'name'|'whatsapp'|'done'>('idle');
 useEffect(()=>{if(lead)leadRepository.save({...lead,transcript:messages.map(message=>`${message.from}: ${message.text}`)})},[lead,messages]);
 const openChat=(item?:Product,action?:string)=>{setProduct(item);setOpen(true);const next=makeLead(item);setLead(next);track('conversation_started',{product:item?.name,action});setMessages([{from:'astreli',text:item?`Hi 👋 You’re looking at the ${item.name}. Want to reserve one, see similar pieces, or ask me anything about it?`:`Hi 👋 I’m ASTRELI, your jewellery stylist. Looking for a piece, the next Night, or just seeing what catches your eye?`}]);if(action==='reserve')setTimeout(()=>reserve(next,item),100)};
 const reserve=(current=lead,item=product)=>{setMessages(value=>[...value,{from:'you',text:'I want this'},{from:'astreli',text:`Beautiful choice${item?` — the ${item.name}`:''}. Shall I note your interest for the next ASTRELI Night, with delivery available if you cannot join?` }]);if(current)setLead({...current,reservationIntent:true,conversationStatus:'reservation_intent'});track('reservation_intent',{product:item?.name})};
 const capture=()=>{setMessages(value=>[...value,{from:'you',text:'Yes, reserve it'},{from:'astreli',text:'Perfect. What should I call you?'}]);setStage('name')};
 const send=()=>{if(!text.trim())return;const value=text.trim();setMessages(items=>[...items,{from:'you',text:value}]);setText('');if(stage==='name'){setLead(current=>current?{...current,name:value}:current);setMessages(items=>[...items,{from:'astreli',text:`Lovely to meet you, ${value}. What’s the best WhatsApp number to keep you updated?`}]);setStage('whatsapp')}else if(stage==='whatsapp'){setLead(current=>current?{...current,whatsapp:value,conversationStatus:'qualified'}:current);setMessages(items=>[...items,{from:'astreli',text:`You’re on the list. We’ll confirm the piece and ${nextNight.date} details personally. No payment has been taken.`}]);setStage('done');track('lead_captured',{product:product?.name})}else setMessages(items=>[...items,{from:'astreli',text:'I’ve noted that. For this preview I can help with the piece, sizing, reservations, ASTRELI Night, or bring in a person.'}])};
 const quick=(label:string)=>{if(label==='I want this')reserve();else if(label==='Reserve for the Night')capture();else if(label==='Talk to a person'){setMessages(items=>[...items,{from:'you',text:label},{from:'astreli',text:'Of course. Leave your name and WhatsApp and a human stylist will continue with the full context.'}]);setLead(current=>current?{...current,conversationStatus:'human_requested'}:current);setStage('name');track('human_handoff',{product:product?.name})}else if(label==='When is ASTRELI Night?'){setMessages(items=>[...items,{from:'you',text:label},{from:'astreli',text:`The next ASTRELI Night is ${nextNight.date} in ${nextNight.city}. The private location is shared with guests. Collect there or choose delivery.`}]);setLead(current=>current?{...current,astreliNightInterest:true,conversationStatus:'event_interested'}:current);track('night_interest')}else if(label==='Show me similar'){const similar=products.filter(item=>item.color===product?.color&&item.id!==product.id).slice(0,2);setMessages(items=>[...items,{from:'you',text:label},{from:'astreli',text:similar.length?`Try ${similar.map(item=>item.name).join(' or ')} — same energy, different shape.`:'Tell me the colour or shape you want and I’ll edit the Drop for you.'}])}else setMessages(items=>[...items,{from:'you',text:label},{from:'astreli',text:'ASTRELI uses genuine lab-grown diamonds in sterling silver, with gold plating only when the design wants warmth. The look comes first; the lab-grown origin makes the price possible.'}])};
 return <StylistContext.Provider value={{openChat}}>{children}<button className="stylist-fab" onClick={()=>openChat()} aria-label="Talk to ASTRELI"><MessageCircle/><span>LET’S TALK</span></button>{open&&<aside className="stylist" aria-label="Talk to ASTRELI" aria-live="polite"><header><div><i>AI</i><span><b>Talk to ASTRELI</b><small>AI stylist · Human when you want one</small></span></div><button onClick={()=>setOpen(false)} aria-label="Close stylist"><X/></button></header>{product&&<Link className="stylist-product" href={`/products/${productSlug(product)}`}><span>{product.name}</span><small>{product.metal}</small></Link>}<div className="stylist-messages">{messages.map((message,index)=><p className={message.from} key={index}>{message.text}</p>)}</div><div className="stylist-actions">{stage==='idle'&&['I want this','Show me similar','Tell me about the diamonds','When is ASTRELI Night?','Talk to a person'].map(label=><button key={label} onClick={()=>quick(label)}>{label}</button>)}{lead?.reservationIntent&&stage==='idle'&&<button className="reserve-action" onClick={()=>quick('Reserve for the Night')}>Reserve for the Night</button>}</div><form onSubmit={event=>{event.preventDefault();send()}}><input value={text} onChange={event=>setText(event.target.value)} placeholder={stage==='name'?'Your first name':stage==='whatsapp'?'WhatsApp with country code':'Ask ASTRELI anything…'}/><button aria-label="Send"><ArrowUp/></button></form><footer><UserRound/> Human takeover always available</footer></aside>}</StylistContext.Provider>}
