'use client';
import Image from 'next/image';
import Link from 'next/link';
import {ArrowRight,MessageCircle,Share2} from 'lucide-react';
import SocialHeader from '@/components/SocialHeader';
import {useStylist} from '@/components/StylistProvider';
import {nextNight} from '@/data/social-commerce';
import {track} from '@/lib/social-analytics';

export default function AstreliNight(){const {openChat}=useStylist();const share=async()=>{track('friend_invite');const url=`${location.origin}/astreli-night?ref=friend`;if(navigator.share)await navigator.share({title:'ASTRELI Night',text:'Come to ASTRELI Night with me.',url});else await navigator.clipboard.writeText(url)};return <><div className="social-announcement">NEXT ASTRELI NIGHT · {nextNight.date.toUpperCase()}</div><SocialHeader/><main className="night-page"><section className="night-hero"><Image src="/images/astreli-night-gallery.jpg" fill priority sizes="100vw" alt="Friends trying jewellery at ASTRELI Night"/><div/><span>JEWELLERY · DRINKS · MUSIC · FRIENDS</span><h1>ASTRELI<br/><em>NIGHT</em></h1><p>{nextNight.city}<br/>{nextNight.date}</p></section><section className="night-statement"><small>EVERY SIX WEEKS</small><h2>Tonight you collect this Drop.<br/>Tonight you discover the next one.</h2><p>Come for the jewellery, stay for the people. Try on the current Drop, collect a reservation, meet a human stylist and see what ASTRELI is revealing next.</p><button onClick={()=>openChat(undefined,'night')}>JOIN ASTRELI NIGHT <MessageCircle/></button><button onClick={share}><Share2/> BRING SOMEONE WITH YOU</button></section><section className="night-details"><div><small>NEXT NIGHT</small><h3>{nextNight.date}<br/>{nextNight.city}</h3><p>{nextNight.venue}</p></div><div><small>WHAT HAPPENS</small><ul><li>Collect your reserved piece</li><li>Try Drop 01 in person</li><li>Discover Drop 02 first</li><li>Bring a friend</li><li>Choose delivery if you cannot attend</li></ul></div></section><section id="previous" className="night-past"><div><Image src="/images/astreli-night-gallery.jpg" fill sizes="60vw" alt="Previous ASTRELI Night"/></div><aside><small>SEEN AT THE LAST NIGHT</small><h2>FLASHES.<br/>FRIENDS.<br/>FIRST LOOKS.</h2><p>Real try-ons, first reservations and enough content to carry ASTRELI into the next six weeks.</p><Link href="/#drop">DISCOVER DROP 01 <ArrowRight/></Link></aside></section><section className="future-drop"><small>REVEALED AT THE NEXT NIGHT</small><h2>DROP 02<br/><em>AFTER HOURS</em></h2><p>Guests see it first. Reservations open after the reveal.</p></section></main><footer className="social-footer"><Link className="social-logo" href="/">ASTRELI<span>LABS IN SILVER</span></Link><nav><Link href="/#drop">Current Drop</Link><Link href="/contact">Contact</Link><Link href="/delivery-returns">Delivery</Link><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></nav><p>© 2026 ASTRELI · KUALA LUMPUR</p></footer></>}
