create extension if not exists pgcrypto;
create type customer_status as enum ('new_lead','engaged','waitlist','reservation_invited','reserved','production','ready','customer','inactive');
create type conversation_status as enum ('open','waiting_customer','waiting_astreli','ai_handled','human_takeover','closed');
create table customers(id uuid primary key default gen_random_uuid(),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),first_name text,last_name text,email text,normalized_email text,whatsapp_number text,normalized_phone text,phone text,preferred_contact_method text,country text,city text,source text,campaign text,utm_source text,utm_medium text,utm_campaign text,utm_content text,utm_term text,first_landing_page text,first_product_viewed text,current_status customer_status not null default 'new_lead',notes text,contact_consent boolean not null default false,contact_consent_at timestamptz,marketing_consent boolean not null default false,marketing_consent_at timestamptz,last_contacted_at timestamptz,last_customer_reply_at timestamptz,last_astreli_reply_at timestamptz);
create unique index customers_normalized_email_uq on customers(normalized_email) where normalized_email is not null;
create unique index customers_normalized_phone_uq on customers(normalized_phone) where normalized_phone is not null;
create table drops(id text primary key,name text not null,slug text unique not null,status text not null check(status in('draft','waitlist_open','reservations_open','in_production','ready','archived')),opens_at timestamptz,reservation_opens_at timestamptz,production_starts_at timestamptz,expected_ready_at timestamptz,active boolean not null default true,notes text);
create table products(id integer primary key,name text not null,slug text unique not null,category text,collection_name text,price numeric(12,2),current_drop boolean not null default false,stylist_library boolean not null default true,waitlist_open boolean not null default false,reservation_open boolean not null default false,active boolean not null default true,internal_status text,metadata jsonb not null default '{}');
create table conversations(id uuid primary key,customer_id uuid references customers(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),channel text not null default 'web' check(channel in('web','email','whatsapp','manual')),status conversation_status not null default 'open',started_from_product_id integer references products(id),started_from_drop_id text references drops(id),source text,assigned_to text,human_takeover boolean not null default false,ai_enabled boolean not null default true,summary text,last_message_at timestamptz,session_id text unique);
create index conversations_customer_idx on conversations(customer_id);create index conversations_last_message_idx on conversations(last_message_at desc);
create table messages(id uuid primary key default gen_random_uuid(),conversation_id uuid not null references conversations(id) on delete cascade,customer_id uuid references customers(id) on delete set null,created_at timestamptz not null default now(),sender_type text not null check(sender_type in('customer','ai','human','system')),sender_name text,content text not null,message_type text not null default 'text',channel text not null default 'web',ai_generated boolean not null default false,human_approved boolean not null default false,metadata jsonb not null default '{}',external_message_id text,message_index integer,unique(conversation_id,message_index));
create index messages_conversation_idx on messages(conversation_id,created_at);create index messages_customer_idx on messages(customer_id);
create table product_interests(id uuid primary key default gen_random_uuid(),customer_id uuid not null references customers(id) on delete cascade,product_id integer not null references products(id),conversation_id uuid references conversations(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),interest_type text not null check(interest_type in('current_drop_waitlist','stylist_library_interest','future_drop_interest','reservation','purchase')),status text not null default 'waitlist',ring_size text,metal_preference text,stone_preference text,variant text,quantity integer not null default 1,budget text,notes text,source text,drop_id text references drops(id),reservation_status text not null default 'not_started',unique(customer_id,product_id,interest_type,drop_id));
create index interests_product_idx on product_interests(product_id,status);create index interests_customer_idx on product_interests(customer_id,created_at desc);
create table reservations(id uuid primary key default gen_random_uuid(),customer_id uuid not null references customers(id),product_id integer not null references products(id),product_interest_id uuid references product_interests(id),drop_id text references drops(id),created_at timestamptz not null default now(),status text not null default 'invited',deposit_required boolean not null default false,deposit_amount numeric(12,2),deposit_paid boolean not null default false,deposit_paid_at timestamptz,payment_reference text,notes text);
create table customer_notes(id uuid primary key default gen_random_uuid(),customer_id uuid not null references customers(id) on delete cascade,note text not null,author text not null,created_at timestamptz not null default now());
create index customer_notes_customer_idx on customer_notes(customer_id,created_at desc);
alter table customers enable row level security;alter table conversations enable row level security;alter table messages enable row level security;alter table products enable row level security;alter table product_interests enable row level security;alter table drops enable row level security;alter table reservations enable row level security;alter table customer_notes enable row level security;
-- No policies intentionally: anon/authenticated roles cannot read customer data. Server service role bypasses RLS.
create or replace function normalize_email(v text) returns text language sql immutable as $$select nullif(lower(trim(v)),'')$$;
create or replace function normalize_phone(v text) returns text language sql immutable as $$select nullif(regexp_replace(coalesce(v,''),'[^0-9+]','','g'),'')$$;
create or replace function ingest_web_lead(payload jsonb) returns jsonb language plpgsql security definer set search_path=public as $$declare c customers; conv conversations; item jsonb; p_id integer; i_type text;begin
 select * into c from customers where (normalize_email(payload->>'email') is not null and normalized_email=normalize_email(payload->>'email')) or (normalize_phone(payload->>'whatsapp') is not null and normalized_phone=normalize_phone(payload->>'whatsapp')) order by created_at limit 1;
 if c.id is null then insert into customers(first_name,email,normalized_email,whatsapp_number,normalized_phone,source,campaign,utm_source,utm_medium,utm_campaign,utm_content,utm_term,first_landing_page,first_product_viewed,current_status,contact_consent,contact_consent_at) values(payload->>'name',normalize_email(payload->>'email'),normalize_email(payload->>'email'),payload->>'whatsapp',normalize_phone(payload->>'whatsapp'),payload->>'source',payload->>'campaign',payload#>>'{utm,utm_source}',payload#>>'{utm,utm_medium}',payload#>>'{utm,utm_campaign}',payload#>>'{utm,utm_content}',payload#>>'{utm,utm_term}',payload->>'landingPage',payload->>'productViewed','engaged',coalesce((payload->>'contactConsent')::boolean,false),case when coalesce((payload->>'contactConsent')::boolean,false) then now() end) returning * into c;
 else update customers set updated_at=now(),first_name=coalesce(payload->>'name',first_name),email=coalesce(normalize_email(payload->>'email'),email),normalized_email=coalesce(normalize_email(payload->>'email'),normalized_email),whatsapp_number=coalesce(payload->>'whatsapp',whatsapp_number),normalized_phone=coalesce(normalize_phone(payload->>'whatsapp'),normalized_phone),current_status=case when payload->>'interestType' is not null then 'waitlist'::customer_status else current_status end where id=c.id returning * into c;end if;
 p_id=nullif(payload->>'productId','')::integer;
 insert into conversations(id,customer_id,started_from_product_id,started_from_drop_id,source,session_id,last_message_at,status) values((payload->>'conversationId')::uuid,c.id,p_id,payload->>'dropId',payload->>'source',payload->>'sessionId',now(),'waiting_astreli') on conflict(id) do update set customer_id=c.id,updated_at=now(),last_message_at=now(),started_from_product_id=coalesce(excluded.started_from_product_id,conversations.started_from_product_id) returning * into conv;
 for item in select * from jsonb_array_elements(coalesce(payload->'messages','[]')) loop insert into messages(conversation_id,customer_id,sender_type,content,channel,ai_generated,human_approved,message_index) values(conv.id,c.id,case when item->>'from'='you' then 'customer' else 'ai' end,item->>'text','web',item->>'from'='astreli',false,(item->>'index')::integer) on conflict(conversation_id,message_index) do nothing;end loop;
 if p_id is not null and payload->>'interestType' is not null then insert into products(id,name,slug,stylist_library,current_drop,waitlist_open,internal_status) values(p_id,coalesce(payload->>'productInterest','ASTRELI design'),'design-'||p_id,true,payload->>'interestType'='product_waitlist',payload->>'interestType'='product_waitlist','captured_from_stylist') on conflict(id) do nothing;i_type=case payload->>'interestType' when 'product_waitlist' then 'current_drop_waitlist' else 'stylist_library_interest' end;insert into product_interests(customer_id,product_id,conversation_id,interest_type,status,ring_size,metal_preference,variant,budget,source,drop_id) values(c.id,p_id,conv.id,i_type,'waitlist',payload->>'ringSize',payload->>'preferredFinish',payload->>'variation',payload->>'budget',payload->>'source',payload->>'dropId') on conflict(customer_id,product_id,interest_type,drop_id) do update set updated_at=now(),conversation_id=excluded.conversation_id,ring_size=coalesce(excluded.ring_size,product_interests.ring_size),metal_preference=coalesce(excluded.metal_preference,product_interests.metal_preference),budget=coalesce(excluded.budget,product_interests.budget);end if;
 return jsonb_build_object('customerId',c.id,'conversationId',conv.id);end$$;
revoke all on function ingest_web_lead(jsonb) from public,anon,authenticated;
create view product_demand as select p.id,p.name,p.slug,p.current_drop,count(distinct pi.customer_id) filter(where pi.interest_type='current_drop_waitlist') waitlist_count,count(distinct pi.customer_id) filter(where pi.interest_type='stylist_library_interest') design_interest_count,count(distinct r.customer_id) reservation_count,count(distinct pi.customer_id) unique_customers,max(pi.created_at) last_interest_at from products p left join product_interests pi on pi.product_id=p.id left join reservations r on r.product_id=p.id group by p.id;
insert into drops(id,name,slug,status,active) values('drop-01','Colour Pop','colour-pop','waitlist_open',true) on conflict do nothing;
insert into products(id,name,slug,category,collection_name,price,current_drop,stylist_library,waitlist_open,reservation_open,internal_status) values
(1,'Blue Lab Diamond Bezel Ring','blue-lab-diamond-bezel-ring','ring','Colour Pop',890,true,true,true,false,'batch_forming'),
(2,'Rainbow Arc Huggies','rainbow-arc-huggies','earrings','Colour Pop',690,true,true,true,false,'batch_forming'),
(4,'Pink Diamond Heart Charm','pink-diamond-heart-charm','charm','Colour Pop',490,true,true,true,false,'batch_forming'),
(10,'Blue Diamond Teardrop Necklace','blue-diamond-teardrop-necklace','necklace','Colour Pop',980,true,true,true,false,'batch_forming'),
(11,'Yellow Diamond Drop Huggies','yellow-diamond-drop-huggies','earrings','Colour Pop',720,true,true,true,false,'batch_forming'),
(12,'Rainbow Diamond Band','rainbow-diamond-band','ring','Colour Pop',1190,true,true,true,true,'reservations_open'),
(102,'Pink Bloom Studs','pink-bloom-studs','earrings','Colour Pop',790,true,true,true,false,'batch_forming'),
(108,'Rainbow Garden Huggies','rainbow-garden-huggies','earrings','Colour Pop',820,true,true,true,false,'batch_forming') on conflict(id) do update set name=excluded.name,price=excluded.price,current_drop=excluded.current_drop,waitlist_open=excluded.waitlist_open;
